# -*- coding: utf-8 -*-
"""Problem 26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqnFuAoI5qmj6EPp9bZrVBP6lEfuLfEB
"""

class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        l = 1
        for r in range(1, len(nums)):
            if nums[r-1] != nums[r]:
                nums[l] = nums[r]
                l += 1 
        return l