# -*- coding: utf-8 -*-
"""Problem 27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqnFuAoI5qmj6EPp9bZrVBP6lEfuLfEB
"""

class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        for i in range(len(nums)):
            while val in nums:
                nums.remove(val)
                
        #print(nums)
        l = len(nums)
        return l