# -*- coding: utf-8 -*-
"""Problem 35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpuuqHzh51WOypOifBiHxffvDTmR1_Sc
"""

class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
        l = 0
        r = len(nums) - 1
        
        while l <=r:
            mid = (l+r)//2
            
            if target == nums[mid]:
                return mid 
            elif target < nums[mid]:
                r = mid - 1
            else:
                l = mid + 1
                
        return l