# -*- coding: utf-8 -*-
"""Problem 217.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpuuqHzh51WOypOifBiHxffvDTmR1_Sc
"""

class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
        num = sorted(nums)

        for i in range(len(num)):
            if len(num) == 1:
                return False
            else:
                if i+1 < len(num):
                    if num[i] == num[i+1]:
                        return True
                        break