# -*- coding: utf-8 -*-
"""Problem 700.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpuuqHzh51WOypOifBiHxffvDTmR1_Sc
"""

# Definition for a binary tree node.
# class TreeNode:
#      def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def searchBST(self, root: Optional[TreeNode], val: int) -> Optional[TreeNode]:
        while root:
            if val == root.val:
                return root
            elif val < root.val:
                root = root.left
            elif val > root.val:
                root = root.right 
        return root