# -*- coding: utf-8 -*-
"""Problem 53.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpuuqHzh51WOypOifBiHxffvDTmR1_Sc
"""

class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        maxsum = nums[0]
        cursum = 0 
        
        for i in nums:
            cursum = cursum + i
            if cursum < 0:
                cursum = 0 
            maxsum = max(cursum, maxsum)
            
        return maxsum