# -*- coding: utf-8 -*-
"""Problem 88.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpuuqHzh51WOypOifBiHxffvDTmR1_Sc
"""

class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        

        temp = [0] * len(nums1)
        
        for i in range(len(nums1)):
            temp[i] = nums1[i]
            
        i = 0
        j = 0
        k = 0

        while k < len(nums1):
            if i < m and j < n:
                if temp[i] < nums2[j]:
                    nums1[k] = temp[i]
                    i += 1
                    k += 1
                else:
                    nums1[k] = nums2[j]
                    j += 1
                    k += 1
            elif i >= m and j < n:
                nums1[k] = nums2[j]
                j += 1
                k += 1
            elif i < m and j >= n:
                nums1[k] = temp[i]
                i += 1
                k += 1